modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="pigpocalypse"
version="1.0.0"
displayName="pigpocalypse2"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="user, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pigpocalypse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.pigpocalypse]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration